package com.traductor.kaqchikel.ui;

import com.traductor.kaqchikel.controller.Busqueda;
import com.traductor.kaqchikel.controller.DiccionarioController;
import com.traductor.kaqchikel.controller.FiltrarPalabra;
import com.traductor.kaqchikel.dao.PalabraDAOimpl;
import com.traductor.kaqchikel.model.Palabra;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.tree.DefaultTreeCellEditor;

public final class MainGUI extends javax.swing.JFrame {

    public MainGUI() {
        initComponents();
        setLocationRelativeTo(null);
        DiccionarioController diccionarioController = new DiccionarioController(this);
        FiltrarPalabra filtrarPalabra = new FiltrarPalabra(this);
        Busqueda busqueda = new Busqueda(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        popupMenu = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        btnLimpiar = new javax.swing.JButton();
        txtField = new javax.swing.JTextField();
        btnTraduccir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnZ = new javax.swing.JButton();
        btnA = new javax.swing.JButton();
        btnB = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnD = new javax.swing.JButton();
        btnE = new javax.swing.JButton();
        btnF = new javax.swing.JButton();
        btnG = new javax.swing.JButton();
        btnH = new javax.swing.JButton();
        btnI = new javax.swing.JButton();
        btnJ = new javax.swing.JButton();
        btnK = new javax.swing.JButton();
        btnL = new javax.swing.JButton();
        btnM = new javax.swing.JButton();
        btnN = new javax.swing.JButton();
        btnO = new javax.swing.JButton();
        btnP = new javax.swing.JButton();
        btnQ = new javax.swing.JButton();
        btnR = new javax.swing.JButton();
        btnS = new javax.swing.JButton();
        btnT = new javax.swing.JButton();
        btnU = new javax.swing.JButton();
        btnV = new javax.swing.JButton();
        btnW = new javax.swing.JButton();
        btnX = new javax.swing.JButton();
        btnY = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();

        lista.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jScrollPane3.setViewportView(lista);

        popupMenu.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        popupMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        popupMenu.setFocusable(false);
        popupMenu.setMaximumSize(new java.awt.Dimension(3, 9));
        popupMenu.setMinimumSize(new java.awt.Dimension(3, 9));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Traductor Kaqchikel");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 90, 46));

        txtField.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        txtField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtField.setName(""); // NOI18N
        txtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldActionPerformed(evt);
            }
        });
        txtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFieldKeyReleased(evt);
            }
        });
        jPanel1.add(txtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 20, 320, 46));

        btnTraduccir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search_icon.png"))); // NOI18N
        btnTraduccir.setText("TRADUCIR");
        btnTraduccir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraduccirActionPerformed(evt);
            }
        });
        jPanel1.add(btnTraduccir, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 130, 46));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 1080, 100));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtArea.setEditable(false);
        txtArea.setColumns(20);
        txtArea.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        txtArea.setRows(5);
        txtArea.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(txtArea);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, 1080, 169));

        jTable1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No", "Español", "Kaqchikel"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.setRowHeight(30);
        jScrollPane2.setViewportView(jTable1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 240, 1080, 310));

        jPanel3.setVerifyInputWhenFocusTarget(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnZ.setText("Z");
        btnZ.setToolTipText("");
        btnZ.setPreferredSize(new java.awt.Dimension(25, 25));
        btnZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZActionPerformed(evt);
            }
        });
        jPanel3.add(btnZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, 40, -1));

        btnA.setText("A");
        btnA.setToolTipText("");
        btnA.setPreferredSize(new java.awt.Dimension(25, 25));
        btnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAActionPerformed(evt);
            }
        });
        jPanel3.add(btnA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, -1));

        btnB.setText("B");
        btnB.setToolTipText("");
        btnB.setPreferredSize(new java.awt.Dimension(25, 25));
        btnB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBActionPerformed(evt);
            }
        });
        jPanel3.add(btnB, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 40, -1));

        btnC.setText("C");
        btnC.setToolTipText("");
        btnC.setPreferredSize(new java.awt.Dimension(25, 25));
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });
        jPanel3.add(btnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 40, -1));

        btnD.setText("D");
        btnD.setToolTipText("");
        btnD.setPreferredSize(new java.awt.Dimension(25, 25));
        btnD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDActionPerformed(evt);
            }
        });
        jPanel3.add(btnD, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 40, -1));

        btnE.setText("E");
        btnE.setToolTipText("");
        btnE.setPreferredSize(new java.awt.Dimension(25, 25));
        btnE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEActionPerformed(evt);
            }
        });
        jPanel3.add(btnE, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 40, -1));

        btnF.setText("F");
        btnF.setToolTipText("");
        btnF.setPreferredSize(new java.awt.Dimension(25, 25));
        btnF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFActionPerformed(evt);
            }
        });
        jPanel3.add(btnF, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 40, -1));

        btnG.setText("G");
        btnG.setToolTipText("");
        btnG.setPreferredSize(new java.awt.Dimension(25, 25));
        btnG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGActionPerformed(evt);
            }
        });
        jPanel3.add(btnG, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 40, -1));

        btnH.setText("H");
        btnH.setToolTipText("");
        btnH.setPreferredSize(new java.awt.Dimension(25, 25));
        btnH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHActionPerformed(evt);
            }
        });
        jPanel3.add(btnH, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 40, -1));

        btnI.setText("I");
        btnI.setToolTipText("");
        btnI.setPreferredSize(new java.awt.Dimension(25, 25));
        btnI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIActionPerformed(evt);
            }
        });
        jPanel3.add(btnI, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 40, -1));

        btnJ.setText("J");
        btnJ.setToolTipText("");
        btnJ.setPreferredSize(new java.awt.Dimension(25, 25));
        btnJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJActionPerformed(evt);
            }
        });
        jPanel3.add(btnJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 40, -1));

        btnK.setText("K");
        btnK.setToolTipText("");
        btnK.setPreferredSize(new java.awt.Dimension(25, 25));
        btnK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKActionPerformed(evt);
            }
        });
        jPanel3.add(btnK, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 40, -1));

        btnL.setText("L");
        btnL.setToolTipText("");
        btnL.setPreferredSize(new java.awt.Dimension(25, 25));
        btnL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLActionPerformed(evt);
            }
        });
        jPanel3.add(btnL, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 40, -1));

        btnM.setText("M");
        btnM.setToolTipText("");
        btnM.setPreferredSize(new java.awt.Dimension(25, 25));
        btnM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMActionPerformed(evt);
            }
        });
        jPanel3.add(btnM, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 40, -1));

        btnN.setText("N");
        btnN.setToolTipText("");
        btnN.setPreferredSize(new java.awt.Dimension(25, 25));
        btnN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNActionPerformed(evt);
            }
        });
        jPanel3.add(btnN, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 40, -1));

        btnO.setText("O");
        btnO.setToolTipText("");
        btnO.setPreferredSize(new java.awt.Dimension(25, 25));
        btnO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOActionPerformed(evt);
            }
        });
        jPanel3.add(btnO, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 40, -1));

        btnP.setText("P");
        btnP.setToolTipText("");
        btnP.setPreferredSize(new java.awt.Dimension(25, 25));
        btnP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPActionPerformed(evt);
            }
        });
        jPanel3.add(btnP, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 40, -1));

        btnQ.setText("Q");
        btnQ.setToolTipText("");
        btnQ.setPreferredSize(new java.awt.Dimension(25, 25));
        btnQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQActionPerformed(evt);
            }
        });
        jPanel3.add(btnQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 40, -1));

        btnR.setText("R");
        btnR.setToolTipText("");
        btnR.setPreferredSize(new java.awt.Dimension(25, 25));
        btnR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRActionPerformed(evt);
            }
        });
        jPanel3.add(btnR, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 40, -1));

        btnS.setText("S");
        btnS.setToolTipText("");
        btnS.setPreferredSize(new java.awt.Dimension(25, 25));
        btnS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSActionPerformed(evt);
            }
        });
        jPanel3.add(btnS, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 40, -1));

        btnT.setText("T");
        btnT.setToolTipText("");
        btnT.setPreferredSize(new java.awt.Dimension(25, 25));
        btnT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTActionPerformed(evt);
            }
        });
        jPanel3.add(btnT, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 40, -1));

        btnU.setText("U");
        btnU.setToolTipText("");
        btnU.setPreferredSize(new java.awt.Dimension(25, 25));
        btnU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUActionPerformed(evt);
            }
        });
        jPanel3.add(btnU, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 40, -1));

        btnV.setText("V");
        btnV.setToolTipText("");
        btnV.setPreferredSize(new java.awt.Dimension(25, 25));
        btnV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVActionPerformed(evt);
            }
        });
        jPanel3.add(btnV, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 40, -1));

        btnW.setText("W");
        btnW.setToolTipText("");
        btnW.setPreferredSize(new java.awt.Dimension(25, 25));
        btnW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWActionPerformed(evt);
            }
        });
        jPanel3.add(btnW, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, 40, -1));

        btnX.setText("X");
        btnX.setToolTipText("");
        btnX.setPreferredSize(new java.awt.Dimension(25, 25));
        btnX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXActionPerformed(evt);
            }
        });
        jPanel3.add(btnX, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 40, -1));

        btnY.setText("Y");
        btnY.setToolTipText("");
        btnY.setPreferredSize(new java.awt.Dimension(25, 25));
        btnY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYActionPerformed(evt);
            }
        });
        jPanel3.add(btnY, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 10, 40, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 1070, 60));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 1110, 70));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 142, 1110, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtArea.setText("");
        txtField.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldActionPerformed

    }//GEN-LAST:event_txtFieldActionPerformed

    // Getters  (muy importante) 
    public JTable getTabla() {
        return jTable1;
    }

    public JTextField getTxtBuscar() {
        return txtField;
    }

    public JButton getBtnBuscar() {
        return btnTraduccir;
    }

    public JTextArea getTextArea() {
        return txtArea;
    }
// menu segerencias

    public JList<String> getLista() {
        return lista;
    }

    public JPopupMenu getPopupMenu() {
        return popupMenu;
    }
    


    // A-Z
    public JButton getJButtonA() {
        return btnA;
    }

    public JButton getJButtonB() {
        return btnB;
    }

    public JButton getJButtonC() {
        return btnC;
    }

    public JButton getJButtonD() {
        return btnD;
    }

    public JButton getJButtonE() {
        return btnE;
    }

    public JButton getJButtonF() {
        return btnF;
    }

    public JButton getJButtonG() {
        return btnG;
    }

    public JButton getJButtonH() {
        return btnH;
    }

    public JButton getJButtonI() {
        return btnI;
    }

    public JButton getJButtonJ() {
        return btnJ;
    }

    public JButton getJButtonK() {
        return btnK;
    }

    public JButton getJButtonL() {
        return btnL;
    }

    public JButton getJButtonM() {
        return btnM;
    }

    public JButton getJButtonN() {
        return btnN;
    }

    public JButton getJButtonO() {
        return btnO;
    }

    public JButton getJButtonP() {
        return btnP;
    }

    public JButton getJButtonQ() {
        return btnQ;
    }

    public JButton getJButtonR() {
        return btnR;
    }

    public JButton getJButtonS() {
        return btnS;
    }

    public JButton getJButtonT() {
        return btnT;
    }

    public JButton getJButtonU() {
        return btnU;
    }

    public JButton getJButtonV() {
        return btnV;
    }

    public JButton getJButtonW() {
        return btnW;
    }

    public JButton getJButtonX() {
        return btnX;
    }

    public JButton getJButtonY() {
        return btnY;
    }

    public JButton getJButtonZ() {
        return btnZ;
    }

    private void btnZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnZActionPerformed

    private void btnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAActionPerformed

    private void btnBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCActionPerformed

    private void btnDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDActionPerformed

    private void btnEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEActionPerformed

    private void btnFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFActionPerformed

    private void btnGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGActionPerformed

    private void btnHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHActionPerformed

    private void btnIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIActionPerformed

    private void btnJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnJActionPerformed

    private void btnKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKActionPerformed

    private void btnLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLActionPerformed

    private void btnMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMActionPerformed

    private void btnNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNActionPerformed

    private void btnOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOActionPerformed

    private void btnPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPActionPerformed

    private void btnQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQActionPerformed

    private void btnRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRActionPerformed

    private void btnSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSActionPerformed

    private void btnTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTActionPerformed

    private void btnUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUActionPerformed

    private void btnVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVActionPerformed

    private void btnWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnWActionPerformed

    private void btnXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXActionPerformed

    private void btnYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnYActionPerformed

    private void btnTraduccirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraduccirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTraduccirActionPerformed

    private void txtFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldKeyPressed

    private void txtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA;
    private javax.swing.JButton btnB;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnD;
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnF;
    private javax.swing.JButton btnG;
    private javax.swing.JButton btnH;
    private javax.swing.JButton btnI;
    private javax.swing.JButton btnJ;
    private javax.swing.JButton btnK;
    private javax.swing.JButton btnL;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnM;
    private javax.swing.JButton btnN;
    private javax.swing.JButton btnO;
    private javax.swing.JButton btnP;
    private javax.swing.JButton btnQ;
    private javax.swing.JButton btnR;
    private javax.swing.JButton btnS;
    private javax.swing.JButton btnT;
    private javax.swing.JButton btnTraduccir;
    private javax.swing.JButton btnU;
    private javax.swing.JButton btnV;
    private javax.swing.JButton btnW;
    private javax.swing.JButton btnX;
    private javax.swing.JButton btnY;
    private javax.swing.JButton btnZ;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JList<String> lista;
    private javax.swing.JPopupMenu popupMenu;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtField;
    // End of variables declaration//GEN-END:variables
}
